# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.11.2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build parser
          command: yarn build:parser
      - run:
          name: Build template string parser
          command: yarn build:template-string-parser
      - run:
          name: Build package
          command: yarn build

      - persist_to_workspace:
          root: ~/repo
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Run unit tests
          command: yarn test
      - run:
          name: Run integration tests
          command: find ./examples/tests -name "*.tab" -exec node ./dist/bin/tablescript.js {} \;

workflows:
  version: 2
  tagged-build:
    jobs:
      - build
      - test:
          requires:
            - build
